[JCV-22-add-functionality-to-send-notifications] - add functionality …
janis-commerce/conversation pull request #1
Opened 2022-05-17 18:39 UTC by moruezabal

**Link al ticket**
[Tarea](https://fizzmod.atlassian.net/browse/JCV-3) / [Subtarea](https://fizzmod.atlassian.net/browse/JCV-22)

**Descripción del requerimiento**
Se deberá crear un [package](https://github.com/janis-commerce/conversation) en donde tenga los siguientes métodos:

- setTopic [String]
- setData [Object]
- setEntity [String|Number]: 
- setEntityId [String|Number]: 
- setUserCreated [String]
- setClientCode [String]
- send --> Es el encargado de realizar la request al MS de conversation

Deberá hacer un [MSCall](https://www.npmjs.com/package/microservice-call) al siguiente endpoint:

```
service: conversation
namespace: message
method: post
```

Se deberá poder inyectarle la [session](https://www.npmjs.com/package/@janiscommerce/api-session) tal cual como se hace en el [package de mailing](https://github.com/janis-commerce/mail/blob/master/lib/mail.js#L169)

**Descripción de la solución**

- Se creó cada función del package
- Se realizó la función send, con lo requerido
- Se agregó la validación por tipo para cada una de las propiedades
- Se añadieron tests para cubrir lo solicitado
- README actualizado

**Datos a tener en cuenta**
- No le agregué validación por campo requeridos, ya que la entidad a la que se envía - message -  [aún está bajo aprobación.](https://fizzmod.atlassian.net/browse/JCV-14)

2022-05-23 20:03 UTC, gastonpereyra commented on README.md
>  const Conversation = require('@janiscommerce/conversation');
1000% seguro que esto no funciona asi, ya que lo que se exporta del package esta en `package.json` en la sección `main` y eso es el `lib/index.js` y este archivo exporta un object con 2 clases.

2022-05-23 20:03 UTC, gastonpereyra commented on lib/conversation.js
>  class Conversation {
Se puede exportar directamente

2022-05-23 20:08 UTC, gastonpereyra commented on lib/conversation.js
> +		if(this.clientCode)
:thinking: Esto podria ser que haya session y además se setee un clientCode ? 

Pregunto porque el sessión ya settea el clientCode

2022-05-23 20:11 UTC, gastonpereyra commented on lib/conversation-validator.js
> +module.exports = class ConversationValidator {
Por como esta hecho el validador no hace falta que haya que instansear la clase para validar todo, podira ser una clase con un método estatico o bien una función directamente.

2022-05-23 20:12 UTC, gastonpereyra commented on lib/conversation-validator.js
> +		if(typeof this.conversation.topic !== 'undefined' && typeof this.conversation.topic !== 'string')
El chequeo del `undefined`  podria ser un método auxiliar y reutilizarlo

2022-05-23 20:13 UTC, gastonpereyra commented on lib/conversation-validator.js
> +		if(typeof this.conversation.topic !== 'undefined' && typeof this.conversation.topic !== 'string')
O bien se podria ser el package de struct

2022-05-23 20:15 UTC, gastonpereyra commented on README.md
> +The methods that you can use to create the notification:
Estaria bueno aclarar que los métodos son `chainable`es decir que se pueden encadenar

2022-05-23 20:16 UTC, gastonpereyra commented on README.md
> +The methods that you can use to create the notification:
Y estaria bueno aclarar no solo el nombre de los métodos sino los parametros también.

2022-05-23 20:16 UTC, gastonpereyra commented on README.md
> +# Available methods
Además aclararia cual es la respuesta del método `send`

2022-05-23 20:17 UTC, gastonpereyra requested changes
Falta adempas agregar los Type Definitions

2022-05-24 13:40 UTC, moruezabal commented on lib/conversation.js
> +		if(this.clientCode)
Claro, hay un setter para setear el clientCode. Sino toma el de la session

2022-05-24 13:48 UTC, moruezabal commented on lib/conversation-validator.js
> +module.exports = class ConversationValidator {
Opté por la clase estática, ya que en el futuro seguramente se le añadirá más validaciones

2022-05-27 00:41 UTC, gastonpereyra commented on README.md
> +The methods that you can use to create the notification: (All these methods are chainable)
Ya sé que pusé que todos los métodos son chainables en la correción anterior, pero también que se aclaré la respuesta del `send`.

Si ves esas 2 cosas, queda que el `send` se pueden chainear pero la descripción dice otra cosa.. 

Entonces esta mal. Una forma de arreglar eso era que se separé y se haga más clara esta parte del Readme, dividir los métodos que son para configurar (que ahi si son todos chainables) y el método para usar, que es el principal, que es el `send`

2022-05-27 00:41 UTC, gastonpereyra commented on README.md
> +# Available methods
No es un H1, ese es el titulo de todo el Readmi que deberia ser el nombre del package

2022-05-27 00:49 UTC, gastonpereyra commented on lib/conversation.js
> +const MicroserviceCall = require('@janiscommerce/microservice-call');
:warning: :warning: 

Hablamos con Manu, y vimos que el usó de este package es muy interno, muy nuestro, esto hace que usar el MS-Call no sea la mejor opción, porque esta request se hace por internet, hay que triggerear APIs, Authorizers, etc.. mucho gasto.

Y tenemos una herramienta para evitar todo esto, que es el nuevo [Invoker](https://github.com/janis-commerce/lambda#children_crossing-service-invoker), de esta manera todo va "por adentro de AWS", y no solo es más rápido sino menos costoso. Esto ya se esta implementado en por ejemplo: https://github.com/janis-commerce/account-process

Asi que recomiendo cambiar el MS-Call por Invoker.. y pegarle al servicio de Conversation pero a una Lambda (se puede pegarle a la Lambda de la API o hacer una nueva Lambda con el mismo fin, ahi definanlo con Manu)

2022-05-27 00:50 UTC, gastonpereyra commented on lib/conversation.js
> +		if(this.clientCode)
Aclaró mi pregunta..

> Si ya tenes la session setteada, es necesario settear este header ?

2022-05-27 00:50 UTC, gastonpereyra requested changes
Comentarios en el PR

2022-06-16 14:16 UTC, moruezabal commented
La lambda que llama el Invoker es nueva, se llama 'saveMessage', devuelve un objeto con el id creado, y en caso de error devuelve un objeto con la propiedad message. Áun no está disponible en Conversation

2022-06-24 22:18 UTC, gastonpereyra commented on package.json
> +    "@janiscommerce/microservice-call": "^4.3.4"
Esto no se usa más, no ?

2022-06-24 22:21 UTC, gastonpereyra commented on lib/conversation.js
>  'use strict';
Notó que faltan los Type Definition

https://fizzmod.atlassian.net/wiki/spaces/JV2/pages/2239299713/Type+Definition+en+package

2022-06-24 22:22 UTC, gastonpereyra commented on lib/conversation.js
> +		const result = await Invoker.serviceClientCall('conversation', 'SaveMessage', this.clientCode, this._conversation);
Se podría retornar directo, no ?

2022-06-24 22:22 UTC, gastonpereyra requested changes
Algunas correciones más

2022-07-06 18:05 UTC, moruezabal commented
En el agregado de la documentación, no encontré ninguna anotación para indicar los metodos `chainables`, intenté describirlo lo mejor posible

2022-07-19 15:39 UTC, gastonpereyra approved these changes

2022-10-15 15:01 UTC, merged